# appimage-builder recipe see https://appimage-builder.readthedocs.io for details
version: 1

script:
  - rm -rf ./AppDir || true
  - export DESTDIR=$PWD/AppDir
  - scripts/install-build-deps.sh
  - mkdir -p build
  - cd build
  - ../scripts/deploy-mauiman.sh
  - ../scripts/deploy-mauikit.sh
  - ../scripts/deploy-mauikit-calendar.sh
  - ../scripts/deploy-agenda.sh

AppDir:
  path: ./AppDir
  app_info:
    id: agenda
    name: Agenda
    icon: agenda
    version: git
    exec: usr/bin/agenda
    exec_args: $@
  runtime:
    env:
      PATH: '${APPDIR}/usr/bin:${APPDIR}/bin:${APPDIR}/usr/lib/x86_64-linux-gnu/libexec/kf5:${PATH}'
      # APPDIR_LIBRARY_PATH: "$APPDIR/lib/x86_64-linux-gnu:$APPDIR/usr/lib:$APPDIR/usr/lib/x86_64-linux-gnu"
      QT_QUICK_CONTROLS_STYLE: "maui-style"
  after_bundle:
    - cd $APPDIR/bin/ && ln -sf bash sh && cd -
  apt:
    arch:
    - amd64
    allow_unauthenticated: true
    sources:
    - sourceline: deb http://archive.ubuntu.com/ubuntu/ noble main restricted universe multiverse
      key_url: 'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3B4FE6ACC0B21F32'
    - sourceline: deb https://packagecloud.io/nitrux/depot/debian/ trixie main
      key_url: 'https://packagecloud.io/nitrux/depot/gpgkey'
    - sourceline: deb https://packagecloud.io/nitrux/testing/debian/ trixie main
      key_url: 'https://packagecloud.io/nitrux/testing/gpgkey'

    include:
    # CORE DEPENDENCIES
    - bash

    # TARGET DEPENDENCIES
    # ⚠ WARNING: DO NOT ADD libc6 AND libstdc++6 TO THIS LIST!
    - akonadi-server
    - libdouble-conversion3
    - libicu74
    - libkf5calendarcore5abi2
    - libkf5codecs5
    - libkf5configcore5
    - libkf5contacts5
    - libkf5coreaddons5
    - libkf5i18n5
    - libkf5itemmodels5
    - libkf5jobwidgets5
    - libkf5kiocore5
    - libkf5notifications5
    - libkf5widgetsaddons5
    - libkf5windowsystem5
    - libkf5xmlgui5
    - libkpim5akonadiagentbase5
    - libkpim5akonadicalendar5
    - libkpim5akonadicontact5
    - libkpim5akonadicore5
    - libkpim5akonadimime5
    - libkpim5akonadinotes5
    - libkpim5akonadiprivate5
    - libkpim5akonadiwidgets5
    - libkpim5akonadixml5
    - libkpim5calendarsupport5
    - libkpim5eventviews5
    - libldap2
    - libmariadb3
    - libmd4c0
    - libpcre2-16-0
    - libqgpgme15
    - libqt5core5a
    - libqt5gui5
    - libqt5publishsubscribe5
    - libqt5qml5
    - libqt5serviceframework5
    - libqt5sql5
    - libqt5systeminfo5
    - libqt5x11extras5
    - mariadb-common
    - qml-module-org-kde-kirigami2
    - qml-module-qtquick-controls2
    - qml-module-qtquick-shapes
    - libkf5iconthemes5
    - libical3
    - libcanberra0
    - libqt5texttospeech5

    exclude:
    - akonadi-backend-mysql
    - akonadi-server
    - bash
    - dbus-bin
    - dbus-daemon
    - dbus-session-bus-common
    - dbus-system-bus-common
    - dirmngr
    - fonts-dejavu-core
    - fonts-dejavu-mono
    - gcc-14-base
    - gnupg
    - gnupg-utils
    - gpg
    - gpg-agent
    - gpgconf
    - gpgsm
    - gpgv
    - kded5
    - keyboxd
    - kf5-messagelib-data
    - kio
    - kio-ldap
    - kmailtransport-akonadi
    - kpackagetool5
    - libaccounts-glib0
    - libaccounts-qt5-1
    - libacl1
    - libapparmor1
    - libargon2-1
    - libasound2
    - libasound2-data
    - libassuan0
    - libaudit-common
    - libaudit1
    - libavahi-client3
    - libavahi-common-data
    - libavahi-common3
    - libavahi-core7
    - libblkid1
    - libbrotli1
    - libbsd0
    - libbz2-1.0
    - libc6
    - libcanberra0
    - libcap-ng0
    - libcap2
    - libcom-err2
    - libcrypt1
    - libcryptsetup12
    - libcups2
    - libdaemon0
    - libdaxctl1
    - libdb5.3
    - libdbus-1-3
    - libdbusmenu-qt5-2
    - libdevmapper1.02.1
    - libdmtx0b
    - libdouble-conversion3
    - libedit2
    - libepoxy0
    - libevdev2
    - libevent-2.1-7
    - libexpat1
    - libfdisk1
    - libffi8
    - libfontconfig1
    - libfreetype6
    - libgcc-s1
    - libgcrypt20
    - libgdbm-compat4
    - libgdbm6
    - libglib2.0-0
    - libgmp10
    - libgnutls30
    - libgpg-error0
    - libgpgme11
    - libgpgmepp6
    - libgrantlee-templates5
    - libgraphite2-3
    - libgssapi-krb5-2
    - libgudev-1.0-0
    - libharfbuzz-subset0
    - libharfbuzz0b
    - libhogweed6
    - libical3
    - libice6
    - libicu74
    - libicu74
    - libidn2-0
    - libimobiledevice6
    - libinput10
    - libjpeg-turbo8
    - libjpeg8
    - libjson-c5
    - libk5crypto3
    - libkaccounts2
    - libkeyutils1
    - libkf5activities5
    - libkf5akonadicalendar-bin
    - libkf5akonadisearch-bin
    - libkf5akonadisearch-plugins
    - libkf5archive-data
    - libkf5archive5
    - libkf5attica5
    - libkf5auth-data
    - libkf5auth5
    - libkf5authcore5
    - libkf5bluezqt-data
    - libkf5bluezqt6
    - libkf5bookmarks-data
    - libkf5bookmarks5
    - libkf5calendarcore5abi2
    - libkf5calendarutils-bin
    - libkf5codecs-data
    - libkf5codecs5
    - libkf5completion-data
    - libkf5completion5
    - libkf5config-data
    - libkf5configcore5
    - libkf5configgui5
    - libkf5configwidgets-data
    - libkf5configwidgets5
    - libkf5contacts-data
    - libkf5contacts5
    - libkf5coreaddons-data
    - libkf5coreaddons5
    - libkf5crash5
    - libkf5dbusaddons-data
    - libkf5dbusaddons5
    - libkf5declarative-data
    - libkf5declarative5
    - libkf5doctools5
    - libkf5globalaccel-bin
    - libkf5globalaccel-data
    - libkf5globalaccel5
    - libkf5globalaccelprivate5
    - libkf5grantleetheme-plugins
    - libkf5guiaddons-bin
    - libkf5guiaddons-data
    - libkf5guiaddons5
    - libkf5holidays-data
    - libkf5holidays5
    - libkf5i18n-data
    - libkf5i18n5
    - libkf5i18nlocaledata5
    - libkf5iconthemes-data
    - libkf5iconthemes5
    - libkf5itemmodels5
    - libkf5itemviews-data
    - libkf5itemviews5
    - libkf5jobwidgets-data
    - libkf5jobwidgets5
    - libkf5kcmutils-data
    - libkf5kcmutils5
    - libkf5kcmutilscore5
    - libkf5kiocore5
    - libkf5kiofilewidgets5
    - libkf5kiogui5
    - libkf5kiontlm5
    - libkf5kiowidgets5
    - libkf5messageviewer-plugins
    - libkf5newstuff-data
    - libkf5newstuff5
    - libkf5newstuffcore5
    - libkf5newstuffwidgets5
    - libkf5notifications-data
    - libkf5notifications5
    - libkf5package-data
    - libkf5package5
    - libkf5plasma5
    - libkf5prison5
    - libkf5purpose-bin
    - libkf5purpose5
    - libkf5quickaddons5
    - libkf5runner5
    - libkf5service-bin
    - libkf5service-data
    - libkf5service5
    - libkf5solid5
    - libkf5solid5-data
    - libkf5sonnet5-data
    - libkf5sonnetcore5
    - libkf5sonnetui5
    - libkf5syndication5abi1
    - libkf5syntaxhighlighting-data
    - libkf5syntaxhighlighting5
    - libkf5textaddons-data
    - libkf5textautocorrectioncore1
    - libkf5textedittexttospeech1
    - libkf5textemoticonscore1
    - libkf5textemoticonswidgets1
    - libkf5textwidgets-data
    - libkf5textwidgets5
    - libkf5threadweaver5
    - libkf5wallet-bin
    - libkf5wallet-data
    - libkf5wallet5
    - libkf5widgetsaddons-data
    - libkf5widgetsaddons5
    - libkf5windowsystem-data
    - libkf5windowsystem5
    - libkf5xmlgui-data
    - libkf5xmlgui5
    - libkgantt2
    - libkmod2
    - libkpim5akonadi-data
    - libkpim5akonadiagentbase5
    - libkpim5akonadicalendar-data
    - libkpim5akonadicalendar5
    - libkpim5akonadicontact-data
    - libkpim5akonadicontact-plugins
    - libkpim5akonadicontact5
    - libkpim5akonadicore5
    - libkpim5akonadimime-bin
    - libkpim5akonadimime-data
    - libkpim5akonadimime5
    - libkpim5akonadinotes-data
    - libkpim5akonadinotes5
    - libkpim5akonadiprivate5
    - libkpim5akonadisearch-data
    - libkpim5akonadisearchcore5
    - libkpim5akonadisearchpim5
    - libkpim5akonadisearchxapian5
    - libkpim5akonadiwidgets5
    - libkpim5calendarsupport-data
    - libkpim5calendarsupport5
    - libkpim5calendarutils-data
    - libkpim5calendarutils5
    - libkpim5contacteditor5
    - libkpim5eventviews-data
    - libkpim5eventviews5
    - libkpim5gapi-data
    - libkpim5gapicore5
    - libkpim5grantleetheme-data
    - libkpim5grantleetheme5
    - libkpim5gravatar-data
    - libkpim5gravatar5
    - libkpim5identitymanagement-data
    - libkpim5identitymanagement5
    - libkpim5identitymanagementwidgets5
    - libkpim5imap-data
    - libkpim5imap5
    - libkpim5ldap-data
    - libkpim5ldap5
    - libkpim5libkdepim-data
    - libkpim5libkdepim5
    - libkpim5libkleo-data
    - libkpim5libkleo5
    - libkpim5mailtransport-data
    - libkpim5mailtransport5
    - libkpim5mbox-data
    - libkpim5mbox5
    - libkpim5messagecomposer5
    - libkpim5messagecore5
    - libkpim5messageviewer5
    - libkpim5mime-data
    - libkpim5mime5
    - libkpim5mimetreeparser5
    - libkpim5pimcommon5
    - libkpim5pimcommonakonadi5
    - libkpim5smtp-data
    - libkpim5smtp5
    - libkpim5templateparser5
    - libkpim5textedit-data
    - libkpim5textedit5
    - libkpim5webengineviewer5
    - libkrb5-3
    - libkrb5support0
    - libksba8
    - libkwalletbackend5-5
    - liblcms2-2
    - libldap2
    - libltdl7
    - liblz4-1
    - liblzma5
    - libmariadb3
    - libmd0
    - libmd4c0
    - libminizip1
    - libmount1
    - libmtdev1
    - libmysqlclient21
    - libncurses6
    - libncursesw6
    - libndctl6
    - libnettle8
    - libnpth0
    - libnspr4
    - libnss3
    - libnuma1
    - libogg0
    - libopenjp2-7
    - libopus0
    - libp11-kit0
    - libpam-modules
    - libpam-systemd
    - libpam0g
    - libpcre2-16-0
    - libpcre2-8-0
    - libperl5.38
    - libplist3
    - libpmem1
    - libpng16-16
    - libpolkit-agent-1-0
    - libpolkit-gobject-1-0
    - libpolkit-qt5-1-1
    - libqca-qt5-2
    - libqgpgme15
    - libqrencode4
    - libqt5core5a
    - libqt5dbus5
    - libqt5gui5
    - libqt5keychain1
    - libqt5network5
    - libqt5positioning5
    - libqt5printsupport5
    - libqt5qml5
    - libqt5qmlmodels5
    - libqt5qmlworkerscript5
    - libqt5quick5
    - libqt5quickcontrols2-5
    - libqt5quicktemplates2-5
    - libqt5quickwidgets5
    - libqt5sql5
    - libqt5sql5-mysql
    - libqt5svg5
    - libqt5texttospeech5
    - libqt5waylandclient5
    - libqt5webchannel5
    - libqt5webengine-data
    - libqt5webenginecore5
    - libqt5webenginewidgets5
    - libqt5widgets5
    - libqt5x11extras5
    - libqt5xml5
    - libre2-10
    - libreadline8
    - libsasl2-2
    - libsasl2-modules-db
    - libseccomp2
    - libselinux1
    - libsharpyuv0
    - libsignon-qt5-1
    - libsm6
    - libsmartcols1
    - libsnappy1v5
    - libsqlite3-0
    - libssl3
    - libstdc++6
    - libsystemd-shared
    - libsystemd0
    - libtasn1-6
    - libtdb1
    - libtinfo6
    - libudev1
    - libunistring5
    - liburing2
    - libusbmuxd6
    - libuuid1
    - libvorbis0a
    - libvorbisfile3
    - libvpx8
    - libwacom-common
    - libwacom9
    - libwebp7
    - libwebpdemux2
    - libwebpmux3
    - libxapian30
    - libxau6
    - libxcb-icccm4
    - libxcb-image0
    - libxcb-keysyms1
    - libxcb-randr0
    - libxcb-record0
    - libxcb-render-util0
    - libxcb-res0
    - libxcb-sync1
    - libxcb-util1
    - libxcb-xinerama0
    - libxcb-xinput0
    - libxcb-xkb1
    - libxcomposite1
    - libxdamage1
    - libxdmcp6
    - libxext6
    - libxfixes3
    - libxkbcommon-x11-0
    - libxkbcommon0
    - libxml2
    - libxrandr2
    - libxrender1
    - libxslt1.1
    - libxtst6
    - libzstd1
    - libzxing3
    - mariadb-client-core
    - mariadb-common
    - mariadb-server-core
    - mysql-common
    - perl
    - perl-base
    - perl-modules-5.38
    - pinentry-curses
    - qml-module-org-kde-bluezqt
    - qml-module-org-kde-kquickcontrolsaddons
    - qml-module-org-kde-prison
    - qml-module-qt-labs-folderlistmodel
    - qml-module-qt-labs-settings
    - qml-module-qtqml
    - qml-module-qtquick-controls2
    - qml-module-qtquick-dialogs
    - qml-module-qtquick-privatewidgets
    - qml-module-qtquick-templates2
    - qml-module-qtquick-window2
    - qml-module-qtquick2
    - qml-module-sso-onlineaccounts
    - qml-module-ubuntu-onlineaccounts
    - readline-common
    - sound-theme-freedesktop
    - systemd-dev
    - tzdata
    - xkb-data
    - zlib1g

  files:
    include:
    - /usr/bin/which
    exclude:
    - usr/include
    - usr/share/man
    - usr/share/doc
    - usr/share/doc/*/README.*
    - usr/share/doc/*/changelog.*
    - usr/share/doc/*/NEWS.*
    - usr/share/doc/*/TODO.*
    - lib/systemd
    - etc/systemd
    - usr/lib/systemd
    - usr/bin/systemd*
    - usr/bin/dpkg*
    - usr/bin/*-linux-gnu-*
    - usr/share/locale

AppImage:
  arch: x86_64
  comp: xz
  file_name: agenda-git-x86_64.AppImage
  update-information: gh-releases-zsync|Nitrux|agenda|git|*x86_64.AppImage.zsync